### ISSUE TITLE
dominance analysis given a correlation matrix

### ISSUE THREAD

**Issue by 1kastner** [bhagatsajan0073/dominance-analysis#10]
**Describe the solution you'd like**
I'd like to do a dominance analysis given a correlation matrix.
I do not have the whole dataset.

**Describe alternatives you've considered**
An alternative would be to refresh my R knowledge and work with https://github.com/clbustos/dominanceAnalysis or ask a colleague to dig out an Excel file we used three years ago.

**Additional context**
I love python and would love to use this library instead of the alternatives listed above.

**Comment by quintshekhar** [comment]
Thanks for suggesting the feature enhancement! We will include that feature in the subsequent release of Dominance-Analysis. Will keep this issue open until we have that feature included.

**Comment by Vibish** [comment]
We have updated the library to perform Dominance Analysis given a Correlation Matrix or a Co-Variance Matrix.

**Comment by 1kastner** [comment]
Thank you so much!
