### ISSUE TITLE
Seeing - ValueError: k should be >=0, <= n_features = 7; got 8. Use k='all' to return all features.

### ISSUE THREAD

**Issue by MichaelSzczepaniak** [bhagatsajan0073/dominance-analysis#30]
Am running DA 1.1.8 on python 3.8 and when I run this command:

`dom_classif_tp = Dominance(data=df_bug_report, target="Y", objective=0, pseudo_r2="mcfadden")`

I see the errors in the attached file errors.txt.  The df_bug_report dataframe can be built by running:

`df_bug_report = pd.read_csv("df_bug_report.csv")  # using the attached csv file`

The attached data file has 50 rows with 7 predictors: X1, X2, X3, X4, X5, X6, X7
X1 and X2 are continuous real variables.  X3 - X7 are binary variables.  The response is the Y column which is also binary.

[errors.txt](https://github.com/dominance-analysis/dominance-analysis/files/10959407/errors.txt)

[df_bug_report.csv](https://github.com/dominance-analysis/dominance-analysis/files/10959370/df_bug_report.csv)

**Comment by MichaelSzczepaniak** [comment]
I was able to work around this issue by setting the top_k parameter.

**Comment by sajanbhagat** [comment]
Thanks, @MichaelSzczepaniak
