### ISSUE TITLE
Failed import with skickit-learn > 1.2

### ISSUE THREAD

**Issue by morganstrom** [bhagatsajan0073/dominance-analysis#31]
**Describe the bug**
When importing dominance-analysis, datasets from sklearn are also imported:

`from sklearn.datasets import load_boston`

This fails for sklearn > 1.2 (https://scikit-learn.org/1.0/modules/generated/sklearn.datasets.load_boston.html)

**To Reproduce**
1. Install a scikit-learn version higher than 1.2
2. Install dominance-analysis
3. Import dominance-analysis

**Expected behavior**
Import doesn't fail

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1
 - Python version 3.10

**Comment by sajanbhagat** [comment]
Hi @morganstrom,

Scikit-learn 1.2 has stopped supporting this dataset and recommended working with an alternative California_housing dataset. Please use another dataset for testing the package if you need any help or face any other issue do raise it. I'll update the dataset to California_dataset in the next release.

Thanks
Sajan

**Comment by sajanbhagat** [comment]
### Use the below code to create dataset 

Import pandas as pd
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
Housing_Data = pd.DataFrame(housing.data,columns=housing.feature_names)
Housing_Data['target']=housing.target

**Comment by sajanbhagat** [comment]
@morganstrom 

Please use the latest version "pip install dominance-analysis==1.1.9" and let us know if any issues you face.

Thanks
Sajan Kumar
