### ISSUE TITLE
Pandas append method deprecated and removed

### ISSUE THREAD

**Issue by mberlinger3** [bhagatsajan0073/dominance-analysis#33]
When calling `dominance_regression.plot_incremental_rsquare().show()`, the following error is raised in pandas >= 2.0:
> AttributeError: 'DataFrame' object has no attribute 'append' 

According to [the release notes in pandas](https://pandas.pydata.org/docs/whatsnew/v1.4.0.html?highlight=append#deprecated-dataframe-append-and-series-append) `pd.append` was deprecated and `pd.concat` should be used instead.

**Comment by sajanbhagat** [comment]
@mberlinger3 thanks for pointing out the depreciation issue. I will fix this issue in an upcoming release.
